import { Layout } from '@/components/layout/Layout'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export default function HomePage() {
  return (
    <Layout>
      <div className="container py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold tracking-tight lg:text-6xl mb-6">
            Smart Calculators with
            <span className="text-primary"> AI Learning</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            Advanced calculators that don't just compute—they teach. 
            Learn concepts, explore formulas, and master skills with AI-powered content.
          </p>
          <div className="flex gap-4 justify-center">
            <Button asChild size="lg">
              <Link href="/calculators">Explore Calculators</Link>
            </Button>
            <Button variant="outline" size="lg" asChild>
              <Link href="/learn">Start Learning</Link>
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <Card>
            <CardHeader>
              <CardTitle>🧮 Advanced Calculators</CardTitle>
              <CardDescription>
                Powerful tools for finance, math, science, and more
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                From compound interest to rocket science, our calculators handle complex calculations with ease.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🤖 AI-Powered Learning</CardTitle>
              <CardDescription>
                Explanations, tutorials, and challenges generated by AI
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Every calculator comes with detailed explanations and interactive learning content.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🌍 Global Accessibility</CardTitle>
              <CardDescription>
                Multi-language support with localized content
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Available in multiple languages with culturally relevant examples and contexts.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  )
}
